openapi: 3.0.0
info:
  title: Dart Shelf Quiz API
  description: API para gerar e responder perguntas de quiz
  version: 1.0.0
paths:
  /quiz/questions/generate:
    get:
      summary: Gera uma pergunta de quiz
      responses:
        '200':
          description: Pergunta gerada com sucesso
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/QuizQuestionDTO'
  /quiz/questions/answer:
    post:
      summary: Envia uma resposta para uma pergunta de quiz
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                questionId:
                  type: string
                  description: ID da pergunta
                answer:
                  type: string
                  description: Resposta para a pergunta
      responses:
        '200':
          description: Resposta enviada com sucesso


components:
  schemas:
    QuizQuestionDTO:
      type: object
      properties:
        id:
          type: integer
          description: ID da pergunta
        question:
          type: string
          description: Texto da pergunta